language: python

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=dhsncats/trustymail
    - DOCKER_USER=jsf9k
    - secure: "A/Qmbd4TpQ1k9PAArd3mkx/vxghcFI0/X2pnUL++AhJKDq2NcV36zm24ot8q8BF5geJYGDi+de3Pcr+FV3Ld5WkSCDHjvhI+rEB9KDO2dJ+rYDnunXMpnKrQ73jYKv0vkLD4drPKv5Cb26nPVnk6KJ7TNVouCrdSHLtdugmvc35FOlOz0vL5WWW44vYj6+ldI/HUAVwO+kBd2pzwH22ZM1uTGreUbydKZEpXEpcVlASP7yHPg+LV4123woLXwZGAt17GHrhID8xeVwRwFfzcEvP3cRt8H9KOjE3WT+edIBnJibXMGzu/qna3bpLbFNZYyS+BWbghju8b44u8l87oIp20nxo73/8jpzE05CKxIeGaaN71c0T016HqYLP2pwUwll/qE6AXrvTLlUX43C9nVB6RTr04k4ooEfqSt4jtRu/xm0fC4wlriPPGoq0OrQFaOHLE2xbA8xw0Jub8KWPTKickZSBNa7RwlOsfifbnWqFZQ5sXsmabMVI1CJNPxXY3tfScSxnPUuXGbRJyjyRag90rstKS888QQXAYstTLSfGhVvTcbsW2gO2Ul+MhcndtQMyDrP/6STBQ41lTaZHoAna0YBnmwfm9Di73CUSz1sHHoVd98mRCIaTvb8ph8KyZOAuQlufDChHzntsq2T5WRAPCfiZsB+/Vgyag+gxh6+4="

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install flake8 pytest-cov pytest coveralls
  - pip install -e .

script:
  - pytest --cov=trustymail
  - flake8 .
  - bash travis_scripts/build_docker_image.sh

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: jsf9k
    password:
      secure: fhEGmCpVdBm/ae4RZXZL7hyiWzx8huFEWJe4YIF/2Qip0BgDlMDfQPoJ/8/DnsuG/+2GC3EEc0ZIl14RwBJ+bn0O+nfcNDsnKTK1ZNK5gtnd+AodHpROT5GUDxl6vb43BShDZm1nc7GaSI0udnpKKB/9xxGc6I1vF6O93VOSziGE7T2BKD1XeyiSHDHXfwT40KIUV8a8yEbjJYvAiVMLKsgxLA/m98Q2kzjqUoCwyAEsLMPaCHKo32DJNLULY+jJ6xTmXqtKRA/w+J5na1TY57RmXlp5kXs/1U44je4Brok0bKOghQfCYW23uB8q1M1GlduexwG6mgWvwJDNp4HKzKswrYG4VUd4SF07Bs7BFZbIuJONYN9xmD/obWQWwNmIoOWa89EOov6/Rp+d4yd15fm+IyO6vnkDBu6HmlyzJDVtIfXWsMnHKkCQtLb35g7CoRKOB6cnp9uvtixjity1caFFL6FnyRMaa2rXpD93Hgs65upAawMkuOROtYlkehBA/Pu2KglllPHpa/kXV6rw+YUKRpm/7sYc1ZykMwGFK2ZF0Rk1de49zrKP4fj1qj1jzD3nFalFi1JExRYwSbDPSVF/Q/ouSKzZ2HhvEPYXTW5E7YQhprDoNT889vNg1oSeTOh7Plk+L0Ukf+YFKMAZMxHn3W1QXnFV+dnCjINpLUY=
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: '3.6'
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.6'
