language: python

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=dhsncats/trustymail
    - DOCKER_USER=jsf9k
    - secure: "IAbtmubLq2hL71aollQEfoV+t9Zbqn4rNVqi5YNerqxvXr6WiDzwmYUujOCnQiHli8xkIU0J8OSPX0aA4cOTxPGiZeNguGuVWmR2ZCB8SMyjbKJOEIpLZv/jG1Be6dVXiJwKwQM3yX4pqPfLIuYkE6S1GAodudPzcJ8xM/h1qzJijknJEqsCJQw43zSHZ/epYulgWcmnCAmaoehZTCjVcW4l8iyVHSNfgO7gu5iWC9y4AIIX96E9TZkSDeud1yqUcORMwfdOl2pHhDh3KnF8HZSOCetTHP7JacLUMJiiCpKN34Xn9RQgjbVKOrF/rcC8WEDrWKn14SFfgUP0dl6lCr6P9HE4aHKvrH/nCyflFOANbEKMywE8DzNA3zd7MC0HQkyb40LAiBSbTD58myUsc+WlmaZyvpJ7akukbmVjVPQWNvs1laz/bqyLdPh4WMqgOTbP7BrgDeIrCVedwdvhqq9KEaoak8RBs/Wb8LisI6j+vAY/HKlVnuIXRL0RNGTko96kBluEpAsWDjls39Hmu5hl1glbqCWDW9+dE0/Zx4MuSt4OVAywMW+lzxA16SdqDLCZqGv00vnPpxuBAvEEQbVtsmQ6lR+fwTYKFEDZM7axRwBlLzIDEzSoz4K0fSq3EuU4mkoVZKcHGnuHuRqaNhce0zzZx3lHdNTm7oa7b0U="

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install flake8 pytest-cov pytest coveralls
  - pip install -e .

script:
  - pytest --cov=trustymail
  - flake8 .
  - bash travis_scripts/build_docker_image.sh

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: jsf9k
    password:
      secure: "t3aZa5VibM+2rlVpPPrbFZ1A601V/IF0fjF6r6D1I8D19cgP3a5bGIuCQ/8Wd5X4JxQ3/5/kGbKiY2tNBPfu+X0Vo+5qgaDNpjumPsa/rsh2cTj1oMigp4mb60rDjChw35Pgl7p2J2u9FSA0zsMh13plgfO2bBYvwSVMNjk+MroUHAGw5af+TEWElJvmr3NvvHdTRWao1d4cSkiVesJx9xr90RBKKUgOa+rS9t2V5z/Q5i9enXK3BFzas3Kfayoset4xcE6azanuiqcJUEoAKhBBh2LrvckKg3oRY6Q7t/JXCgWPsYrAIe0KwfHAopBFoNoZRf2M35cg10lj7IHS2IThY1moaisdxWIOeWQPblTeDAUbXx6hzCCxPhWCVhUowpPU2/Kqu9vSVqPymcSy2+q7MOeEda0hobMl4qvQT6apzeIWoRY9YO45aFWtep2dz7NvWDV566K/UpyKrfdvVQNbc+DxBJ087Tm6SbplEYpz1SXHz9oYFLyp/19nEG/GkGYPWmRHawRN731lW2/1DRNieesf4aYpN3ykNOCWJk0ahFMlkiK4Q9EWxMzxJb3f73r+7yak0/g8t4c1Ga8uI6coKfRD84Lsld91LvyDi6RlXuumC9UtWHH2m6f+MPx7kcPyY6uTsJJBfjHyrZJGgMpm2thjdO+FObyNPEn2N44="
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: '3.6'
  - provider: script
    script: bash travis_scripts/deploy_to_docker_hub.sh
    on:
      tags: true
      python: '3.6'
